{% set version = '1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sid
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SID_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SID/SID_{{ version }}.tar.gz
  sha256: 3cc0828f1cef6c0cc998babede6e6f6888fd9b01cd430bfda5802f9c89ff8690

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-matrix
    - r-rbgl
    - r-igraph
    - r-pcalg

  run:
    - r-base
    - r-matrix
    - r-rbgl
    - r-igraph
    - r-pcalg

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('SID')"           # [not win]
    - "\"%R%\" -e \"library('SID')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=SID
  license: FreeBSD
  summary: "The code computes the structural intervention distance (SID) between a true directed
    acyclic graph (DAG) and an estimated DAG. Definition and details about the implementation
    can be found in J. Peters and P. B\xFChlmann: \"Structural intervention distance
    (SID) for evaluating causal graphs\", Neural Computation 27, pages 771-799, 2015."

  license_family: BSD

# The original CRAN metadata for this package was:

# Package: SID
# Type: Package
# Title: Structural Intervention Distance
# Version: 1.0
# Date: 2015-03-07
# Author: Jonas Peters
# Encoding: UTF-8
# Imports: pcalg, igraph, RBGL, Matrix
# Maintainer: Jonas Peters <jonas.peters@tuebingen.mpg.de>
# Description: The code computes the structural intervention distance (SID) between a true directed acyclic graph (DAG) and an estimated DAG. Definition and details about the implementation can be found in J. Peters and P. Buhlmann: "Structural intervention distance (SID) for evaluating causal graphs", Neural Computation 27, pages 771-799, 2015.
# License: FreeBSD
# Packaged: 2015-03-07 14:35:03 UTC; jopeters
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2015-03-07 17:35:02

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
